### ISSUE TITLE
InfraSIM in docker script issues

### ISSUE THREAD

**Issue by panpan0000** [InfraSIM/tools#51]
I've several comments of bugs in https://github.com/InfraSIM/tools/commit/a857737a57c4d065efbda7f1ba072f02af08b6bf

example, IP setting, the NIC STP setting ...etc.

I believe they will impact the InfraSIM@docker usage.

@fub2   @chenge3

**Comment by fub2** [comment]
Thank you @panpan0000! most of them you already got clear idea. do you mind to pr them?

**Comment by fub2** [comment]
Updated script https://github.com/InfraSIM/tools/blob/master/docker/docker.py fixed all this.
